import { useState, type ChangeEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, ImagePlus, LockKeyhole, LogOut, PackageCheck, ShieldPlus, UploadCloud, UsersRound } from "lucide-react";
import { PageIntro, SiteLayout } from "@/components/SiteShell";
import { apiGet, apiPatch, apiPost, apiPut } from "@/lib/api";
import { beginSession, endSession, useSession } from "@/lib/session";
import type { AdminLoginResponse, Order, PaymentQr, User } from "@/lib/types";

type AdminView = "orders" | "qr" | "admins";

function orderStatus(status: Order["status"]) {
  return status === "pending_approval" ? "Awaiting approval" : status === "confirmed" ? "Confirmed" : "Cancelled";
}

function AdminOrderCard({ order }: { order: Order }) {
  const queryClient = useQueryClient();
  const [deliveryFee, setDeliveryFee] = useState(String(order.approved_delivery_fee ?? order.estimated_delivery_fee));
  const mutation = useMutation({
    mutationFn: (status: "confirmed" | "cancelled") => apiPatch<Order>(`/admin/orders/${order.id}`, { status, approved_delivery_fee: Number(deliveryFee) }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["admin-orders"] }),
  });

  return <article className="rounded-2xl border border-line bg-white p-6 sm:p-8" data-testid={`admin-order-${order.id}`}>
    <div className="flex flex-col justify-between gap-5 lg:flex-row">
      <div><div className="flex flex-wrap items-center gap-3"><p className="label text-green" data-testid={`admin-order-number-${order.id}`}>{order.order_number}</p><span className={`rounded-full px-3 py-1 text-[10px] font-bold uppercase tracking-[0.1em] ${order.status === "confirmed" ? "bg-green/10 text-green" : order.status === "cancelled" ? "bg-red-100 text-red-700" : "bg-lime/15 text-forest"}`} data-testid={`admin-order-status-${order.id}`}>{orderStatus(order.status)}</span></div><h3 className="mt-3 font-heading text-3xl text-forest">{order.customer_name}</h3><p className="mt-2 text-sm text-ink/55">{order.customer_email} · {order.customer_phone}</p><p className="mt-2 max-w-xl text-sm leading-relaxed text-ink/60">{order.delivery_address}, {order.pincode}</p></div>
      <div className="text-left lg:text-right"><p className="font-heading text-4xl text-forest" data-testid={`admin-order-total-${order.id}`}>₹{order.total}</p><p className="text-xs text-ink/50">{order.payment_method === "cod" ? "Cash on Delivery" : "PhonePe QR"} · {order.payment_status.replaceAll("_", " ")}</p></div>
    </div>
    <div className="mt-6 grid gap-5 border-y border-line py-5 lg:grid-cols-[1fr_280px]">
      <div>{order.items.map((item) => <p key={`${item.product_slug}-${item.plan}-${item.weight}`} className="mt-2 flex justify-between gap-3 text-sm"><span>{item.name} · {item.weight} · {item.plan === "gyoc" ? "G.Y.O.C." : "Regular"} × {item.quantity}</span><strong>₹{item.line_total}</strong></p>)}</div>
      <div className="rounded-xl bg-sage p-4 text-sm"><div className="flex justify-between"><span>Subtotal</span><span>₹{order.subtotal}</span></div><div className="mt-2 flex justify-between"><span>COD fee</span><span>₹{order.cod_fee}</span></div><div className="mt-2 flex justify-between"><span>Estimated delivery</span><span>₹{order.estimated_delivery_fee}</span></div><p className="mt-2 text-xs text-ink/50">Customer estimate: {order.estimated_distance_km} km</p></div>
    </div>
    {order.notes && <p className="mt-5 rounded-xl bg-cream p-4 text-sm text-ink/60" data-testid={`admin-order-notes-${order.id}`}><strong className="text-forest">Customer note:</strong> {order.notes}</p>}
    <div className="mt-6 flex flex-col gap-3 sm:flex-row sm:items-end"><label className="text-[10px] font-bold uppercase tracking-[0.12em] text-green">Approved delivery fee (₹)<input type="number" min="0" max="5000" value={deliveryFee} onChange={(event) => setDeliveryFee(event.target.value)} className="mt-2 w-full rounded-xl border border-line bg-cream px-4 py-3 text-sm normal-case text-ink sm:w-48" data-testid={`admin-delivery-fee-${order.id}`} /></label><button type="button" onClick={() => mutation.mutate("confirmed")} disabled={mutation.isPending} className="rounded-full bg-forest px-5 py-3 text-xs font-bold uppercase tracking-[0.1em] text-white disabled:opacity-50" data-testid={`admin-confirm-order-${order.id}`}>Approve & confirm</button><button type="button" onClick={() => mutation.mutate("cancelled")} disabled={mutation.isPending} className="rounded-full border border-red-300 px-5 py-3 text-xs font-bold uppercase tracking-[0.1em] text-red-700 disabled:opacity-50" data-testid={`admin-cancel-order-${order.id}`}>Cancel order</button>{mutation.isSuccess && <span className="inline-flex items-center gap-1 text-xs font-semibold text-green"><CheckCircle2 size={14} /> Customer email sent</span>}</div>
  </article>;
}

function OrdersPanel() {
  const ordersQuery = useQuery({ queryKey: ["admin-orders"], queryFn: () => apiGet<Order[]>("/admin/orders"), retry: false });
  return <section data-testid="admin-orders-panel"><div className="flex flex-col justify-between gap-3 border-b border-line pb-6 sm:flex-row sm:items-end"><div><p className="label text-green">Stored orders</p><h2 className="mt-2 font-heading text-5xl text-forest">Order approvals</h2></div><p className="text-sm text-ink/50">{ordersQuery.data?.length ?? 0} orders</p></div>{ordersQuery.data?.length ? <div className="mt-8 space-y-5">{ordersQuery.data.map((order) => <AdminOrderCard key={order.id} order={order} />)}</div> : <div className="mt-8 rounded-2xl border border-line bg-white p-10 text-center"><PackageCheck className="mx-auto text-green" size={32} /><h3 className="mt-4 font-heading text-3xl text-forest">No orders yet.</h3></div>}</section>;
}

function QrPanel() {
  const queryClient = useQueryClient();
  const [selectedImage, setSelectedImage] = useState<string | null>(null);
  const [error, setError] = useState("");
  const qrQuery = useQuery({ queryKey: ["admin-payment-qr"], queryFn: () => apiGet<PaymentQr>("/payment-qr"), retry: false });
  const uploadMutation = useMutation({ mutationFn: () => apiPut<PaymentQr>("/payment-qr", { qr_data_url: selectedImage }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["payment-qr"] }); queryClient.invalidateQueries({ queryKey: ["admin-payment-qr"] }); setSelectedImage(null); setError(""); }, onError: () => setError("Could not save the QR image.") });

  function handleFile(event: ChangeEvent<HTMLInputElement>) {
    const file = event.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith("image/")) { setError("Please choose an image file."); return; }
    const reader = new FileReader();
    reader.onload = () => setSelectedImage(String(reader.result));
    reader.readAsDataURL(file);
  }

  return <section data-testid="admin-qr-panel"><p className="label text-green">Payment settings</p><h2 className="mt-2 font-heading text-5xl text-forest">Payment QR</h2><div className="mt-8 grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div className="rounded-2xl border border-line bg-white p-6 sm:p-8"><div className="flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-green"><ImagePlus size={16} /> Current public QR</div>{qrQuery.data?.qr_data_url ? <img src={qrQuery.data.qr_data_url} alt="Current Micro Might payment QR" className="mx-auto mt-7 aspect-square w-full max-w-[270px] rounded-xl object-contain" data-testid="admin-current-qr-image" /> : <div className="mx-auto mt-7 grid aspect-square w-full max-w-[270px] place-items-center rounded-xl border-2 border-dashed border-line bg-cream"><p className="font-heading text-3xl text-forest">No QR uploaded</p></div>}</div><div className="rounded-2xl border border-line bg-white p-6 sm:p-8"><p className="label text-green">Replace payment QR</p><h3 className="mt-3 font-heading text-4xl text-forest">Add a clear QR image.</h3><label className="mt-7 flex min-h-44 cursor-pointer flex-col items-center justify-center rounded-2xl border-2 border-dashed border-green/35 bg-sage/40 p-6 text-center" data-testid="admin-file-upload-area"><UploadCloud className="text-green" size={28} /><span className="mt-3 text-sm font-bold text-forest">Choose QR image</span><input type="file" accept="image/png,image/jpeg,image/webp" onChange={handleFile} className="sr-only" data-testid="admin-qr-file-input" /></label>{selectedImage && <img src={selectedImage} alt="Selected QR preview" className="mx-auto mt-5 aspect-square max-h-48 rounded-xl object-contain" data-testid="admin-selected-qr-preview" />}{error && <p className="mt-4 text-sm text-red-700">{error}</p>}<button type="button" disabled={!selectedImage || uploadMutation.isPending} onClick={() => uploadMutation.mutate()} className="mt-6 inline-flex w-full items-center justify-center gap-2 rounded-full bg-forest px-5 py-4 text-xs font-bold uppercase tracking-[0.12em] text-white disabled:opacity-40" data-testid="admin-save-qr-button"><UploadCloud size={16} /> {uploadMutation.isSuccess ? "Saved" : "Save payment QR"}</button></div></div></section>;
}

function AdminsPanel() {
  const queryClient = useQueryClient();
  const [form, setForm] = useState({ name: "", email: "", username: "", password: "" });
  const [error, setError] = useState("");
  const adminsQuery = useQuery({ queryKey: ["admin-users"], queryFn: () => apiGet<User[]>("/admin/admins"), retry: false });
  const mutation = useMutation({ mutationFn: () => apiPost<User>("/admin/admins", form), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["admin-users"] }); setForm({ name: "", email: "", username: "", password: "" }); setError(""); }, onError: () => setError("Could not add this admin. The email or username may already exist.") });
  return <section data-testid="admin-users-panel"><p className="label text-green">Access control</p><h2 className="mt-2 font-heading text-5xl text-forest">Admin users</h2><div className="mt-8 grid gap-8 lg:grid-cols-[0.9fr_1.1fr]"><div className="space-y-3">{adminsQuery.data?.map((admin) => <div key={admin.id} className="rounded-2xl border border-line bg-white p-5" data-testid={`admin-user-${admin.id}`}><div className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-full bg-sage text-green"><UsersRound size={17} /></span><div><p className="font-semibold text-forest">{admin.name}</p><p className="text-xs text-ink/50">@{admin.username} · {admin.email}</p></div></div></div>)}</div><form className="rounded-2xl border border-line bg-white p-6 sm:p-8" onSubmit={(event) => { event.preventDefault(); mutation.mutate(); }} data-testid="add-admin-form"><ShieldPlus className="text-green" size={24} /><h3 className="mt-4 font-heading text-3xl text-forest">Add another admin</h3><div className="mt-6 grid gap-4 sm:grid-cols-2"><label className="text-xs font-bold uppercase tracking-[0.1em] text-green">Name<input required value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} className="mt-2 w-full rounded-xl border border-line bg-cream px-4 py-3 text-sm normal-case text-ink" data-testid="new-admin-name-input" /></label><label className="text-xs font-bold uppercase tracking-[0.1em] text-green">Email<input required type="email" value={form.email} onChange={(event) => setForm({ ...form, email: event.target.value })} className="mt-2 w-full rounded-xl border border-line bg-cream px-4 py-3 text-sm normal-case text-ink" data-testid="new-admin-email-input" /></label><label className="text-xs font-bold uppercase tracking-[0.1em] text-green">Username<input required minLength={3} value={form.username} onChange={(event) => setForm({ ...form, username: event.target.value })} className="mt-2 w-full rounded-xl border border-line bg-cream px-4 py-3 text-sm normal-case text-ink" data-testid="new-admin-username-input" /></label><label className="text-xs font-bold uppercase tracking-[0.1em] text-green">Temporary password<input required type="password" minLength={8} value={form.password} onChange={(event) => setForm({ ...form, password: event.target.value })} className="mt-2 w-full rounded-xl border border-line bg-cream px-4 py-3 text-sm normal-case text-ink" data-testid="new-admin-password-input" /></label></div>{error && <p className="mt-4 text-sm text-red-700">{error}</p>}<button type="submit" disabled={mutation.isPending} className="mt-6 w-full rounded-full bg-forest px-5 py-4 text-xs font-bold uppercase tracking-[0.1em] text-white disabled:opacity-50" data-testid="add-admin-submit-button">Add admin</button></form></div></section>;
}

export default function Admin() {
  const session = useSession();
  const currentAdmin = session.data?.user?.role === "admin" ? session.data.user : null;
  const [view, setView] = useState<AdminView>("orders");
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [error, setError] = useState("");
  const loginMutation = useMutation({ mutationFn: () => apiPost<AdminLoginResponse>("/admin/login", { username, password }), onSuccess: (result) => { beginSession(result.user); setError(""); }, onError: () => setError("That admin login did not match.") });

  if (!currentAdmin) return <SiteLayout><PageIntro eyebrow="Admin dashboard" title="Run Micro Might orders with confidence." description="Sign in to approve delivery fees, confirm customer orders, manage the payment QR and add trusted admin users." /><section className="bg-cream px-5 py-14 sm:py-20 lg:px-10 lg:py-24" data-testid="admin-section"><div className="mx-auto max-w-md rounded-[2rem] border border-line bg-white p-7 shadow-[0_15px_45px_rgba(0,0,0,0.05)] sm:p-10" data-testid="admin-login-card"><div className="grid h-12 w-12 place-items-center rounded-full bg-sage text-forest"><LockKeyhole size={21} /></div><h2 className="mt-6 font-heading text-4xl text-forest">Admin sign in</h2><form className="mt-7 space-y-4" onSubmit={(event) => { event.preventDefault(); loginMutation.mutate(); }} data-testid="admin-login-form"><label className="block text-xs font-bold uppercase tracking-[0.12em] text-green">Username<input required value={username} onChange={(event) => setUsername(event.target.value)} className="mt-2 w-full rounded-xl border border-line bg-cream px-4 py-3 text-sm normal-case text-ink" data-testid="admin-username-input" /></label><label className="block text-xs font-bold uppercase tracking-[0.12em] text-green">Password<input required type="password" value={password} onChange={(event) => setPassword(event.target.value)} className="mt-2 w-full rounded-xl border border-line bg-cream px-4 py-3 text-sm normal-case text-ink" data-testid="admin-password-input" /></label>{error && <p className="text-sm text-red-700" data-testid="admin-login-error">{error}</p>}<button type="submit" disabled={loginMutation.isPending} className="w-full rounded-full bg-forest px-5 py-4 text-xs font-bold uppercase tracking-[0.12em] text-white disabled:opacity-60" data-testid="admin-login-submit-button">{loginMutation.isPending ? "Checking..." : "Enter dashboard"}</button></form><div className="mt-7 border-t border-line pt-5 text-sm text-ink/55" data-testid="admin-demo-credentials"><p className="font-bold text-forest">Demo admin login</p><p className="mt-2">Username: <code className="rounded bg-sage px-1.5 py-0.5">admin</code></p><p className="mt-1">Password: <code className="rounded bg-sage px-1.5 py-0.5">micromight2026</code></p></div></div></section></SiteLayout>;

  return <SiteLayout><section className="bg-cream px-5 py-14 sm:py-20 lg:px-10 lg:py-24" data-testid="admin-dashboard"><div className="mx-auto max-w-[1180px]"><div className="flex flex-col justify-between gap-5 border-b border-line pb-7 sm:flex-row sm:items-end"><div><p className="label text-green">Signed in as {currentAdmin.name}</p><h1 className="mt-2 font-heading text-5xl text-forest sm:text-6xl">Admin workspace</h1></div><button type="button" onClick={() => endSession()} className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-[0.12em] text-forest" data-testid="admin-logout-button"><LogOut size={15} /> Sign out</button></div><nav className="my-8 flex gap-2 overflow-x-auto pb-2" aria-label="Admin sections">{(["orders", "qr", "admins"] as AdminView[]).map((item) => <button key={item} type="button" onClick={() => setView(item)} className={`shrink-0 rounded-full px-5 py-3 text-xs font-bold uppercase tracking-[0.1em] ${view === item ? "bg-forest text-white" : "border border-line bg-white text-forest"}`} data-testid={`admin-view-${item}`}>{item === "qr" ? "Payment QR" : item}</button>)}</nav>{view === "orders" ? <OrdersPanel /> : view === "qr" ? <QrPanel /> : <AdminsPanel />}</div></section></SiteLayout>;
}